package com.foxseventeen.pearlrelay.relay;

public enum RelayFailure {
	RELAY_NOT_FOUND,
	RELAY_REQUIRES_RESAVE,
	DIMENSION_UNAVAILABLE,
	SPAWN_CHUNK_UNLOADED,
	TARGET_CHUNK_UNLOADED,
	SPAWN_POSITION_BLOCKED,
	TARGET_BLOCK_CHANGED,
	TARGET_UNREACHABLE,
	OWNED_PEARL_NOT_FOUND,
	EXECUTION_ALREADY_ACTIVE,
	FAKE_PLAYER_NAME_IN_USE;

	public String code() {
		return name();
	}
}
